autoSectionPath = "src"
gitSourceBranch = "main"
title = "PromiseUtilities"

[docusaurus]
tagline = "Utilities for Promises."

[navbar.logo]
alt = "Bura Logo"
src = "bura-logo.webp"

[[navbar.items]]
items = [{ href = "https://eryn.io/roblox-lua-promise/", label = "Promise" }]
label = "Relevant Docs"
position = "right"
type = "dropdown"

[home]
enabled = true
includeReadme = false

# [[home.features]]
# title = "Immutability"
# description = "Completely immutable data."
